### ISSUE TITLE
Add gometalinter to build

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/agones#163]

**Comment by markmandel** [comment]
Just to add more details - `gometalinter` is in the build image for local usage, but the fun/tricky part will be ignoring the autogenerated code. The good thing is, all the autogenerated code does have an appropriate headers, so it should be straight forward to exclude them.

**Comment by EricFortin** [comment]
@enocom Have you started working on this? If not I’d like to help.

**Comment by markmandel** [comment]
I'm not seeing any issues here - if nothing else, also happy for a build to simply fail if any linter fails.

gometalinter will let you put in a comment to ignore a specific line if you feel it's a false positive - so we can work around anything we specifically disagree with (unless it's generated code, as we talk about above, and we can `--exclude` that, I believe).

@enocom any extra thoughts on your end?

**Comment by enocom** [comment]
Making the build fail on `vetshadow` is a good idea. I'm in favor of getting it running and tuning it accordingly.

**Comment by markmandel** [comment]
I already have some `// nolint ` declarations around the codebase as I tend to use `gometalinter` as I develop.

**Comment by EricFortin** [comment]
Hi again, I worked on this a little more and would like your opinion on some topics. 

As an aside, I discovered that the `vetshadow` linter does indeed generate warnings and those are treated as errors(good) but I have been hit by the exact problem I was describing earlier where I was using an old master branch(my build image was quite old) that contained a bug that prevented it from reporting. I updated my build image and everything is fine now.

As for skipping the generated file, there is currently no way to skip a file based on its content. There is an [issue](https://github.com/alecthomas/gometalinter/issues/270) opened on it but not much work done though.

`gometalinter` allows skipping folder or individual files and I made it work like this for my first iteration. Since @markmandel mentioned skipping on presence of go [standard generated comment](https://github.com/golang/go/issues/13560) I am wondering if I should implement this. As stated, finding those files is easy but then I either need to generate a json config file or compose an enormous command line for `gometalinter`. What is your opinion on this?

**Comment by EricFortin** [comment]
Here is an example of my config file at the moment:
```
{
  "EnableAll": true,
  "skip": [
    "vendor",
    "client"
  ],
  "Exclude": [
    "pkg/apis/stable/v1alpha1/zz_generated.deepcopy.go"
  ],
  "deadline": "300s"
}
```

If I generated it, all filenames would be in the exclude list.

**Comment by EricFortin** [comment]
You would add it after we generate the file?

**Comment by enocom** [comment]
Yeah, as a minor and one time annoyance. The risk is subsequent file generations deletes the line. But by all means, since you're seeing how painful each option is, let's go with what seems best to you.

**Comment by markmandel** [comment]
We add licence headers to all generated files - but they all use different methods. Making sure it hits _just_ before the `package` declaration could be.... interesting :smile: 

Doing a grep for "autogenerated" and excluding those files is probably the best bet.

**Comment by EricFortin** [comment]
Good I’ll do the grep then. Thank you!
