### ISSUE TITLE
Minikube does not start with 0.26.x

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#192]
The [instructions for starting a minikube cluster](https://github.com/GoogleCloudPlatform/agones/blob/master/docs/installing_agones.md#starting-minikube) current hang when the cluster starts up.

This also affects the [development build path for minikube](https://github.com/GoogleCloudPlatform/agones/tree/master/build#running-a-test-minikube-cluster) as well.

This ticket is to track any progress, and track any valid workarounds or configuration changes we need to do on our end.

Could be related to [this minikube issue](https://github.com/kubernetes/minikube/issues/2765) - seems like there are several issues in the tracker regarding hanging on start.

**Workaround**: [Install 0.25.2](https://github.com/kubernetes/minikube/releases/tag/v0.25.2)

**Comment by newphew92** [comment]
To be clear, the hang up happens when you have extra config like so:

alias ministart='miniclean;swapoff -a;minikube start --kubernetes-version v1.9.0 --vm-driver=none \
--extra-config=apiserver.admission-control="NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota" \
;minikube profile agones'

**Comment by newphew92** [comment]
I tried on both 26.0 and 25.2, adding the bootstrapper flag makes it hang in both case on start.

**Comment by markmandel** [comment]
Closing this because we are now working on 0.28 - See #273
