### ISSUE TITLE
As matchmaker, I want to be able to allocate a specific server instance

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#297]
In the context of server registering themselves to the matchmaker (as opposed to matchmaker requesting a random server), it would be useful to allow the matchmaker to allocate a server specified by its "AgonesId" - i.e. pod name. This call is allowed to fail if the server is not online anymore, is not Ready or it's scheduled for decommission.

This eliminates the need of servers allocating themselves which is more complicated to implement.

**Comment by Kuqd** [comment]
Allocation hint are definitively interesting 👍

**Comment by markmandel** [comment]
I can see this becoming a configuration option on `FleetAllocation` although i would tie it to the `GameServer` record, rather than the pod.

Something like a 'required-gameserver`  (fail if it can't allocate the `GameServer`) and a `preferred-gameserver` (where if it can allocate that `GameServer`, but if it can't it just chooses another one).

That being said I'd love to learn more about the use case for this - what's the impetus for the matchmaker to pick a gameserver rather than let Agones do it for you?

**Comment by victor-prodan** [comment]
Hum ... I think I explained the reason in the request :-|

**Comment by markmandel** [comment]
So I understand what you want to do, and your preference, but I just don't understand why you want to do it. Specifically, "This eliminates the need of servers allocating themselves which is more complicated to implement." -- In the Agones model, GameServers don't allocate themselves, Agones decides which one to Allocate, so this left me a tad confused.

From my perspective, it seems simpler to just ask for a free server from the Fleet, rather than the matchmaker doing essentially the same work as Agones here.

That being said, it's entirely possible I'm not aware of the matchmaking->allocation flow you wish to have, so if you could expand on this, I'd definitely love to hear it :smile:

**Comment by victor-prodan** [comment]
ok, we talked about this on the #users channel so I thought it was clear.

there are games that use a session browser model for matchmaking, în which people can start servers at home that register to the session browser, and the players that want to play chose from there. This îs the 'old-school' way, invented before games had their own servers and online services. While old, this model is still very popular for indie games , who can not afford to develop and host their own matchmaking servers so they use free services like Steam.

(If I understood correctly, this is also the case of @CrimsonZen)

And Agones, being open source, should be indie-friendly 😁

Another reason for me is that it allows to create a matchmaking flow in which all servers are equal, no matter how they were started - local machine, cloud, etc. You dont need to do one matchmaking for direct mode and one for cloud. 

And it also allows a simple, seamless transition from session browser model to quickplay model. You start with a session browser and when you can afford it, make a quickplay server that just picks servers from your existing browser.

Another reason is that I think it will help games that want to transition from IaaS to PaaS. Most MMOs (mmo-likes) are using IaaS and do their own server instance management. They could use Agones for elastic cluster expansion while keeping the rest of the servers on IaaS. I dont know any real example, it's just my intuition.

**Comment by victor-prodan** [comment]
Also, related to this I would like to mention that I3D API allows productions to do all kind of micromanagement with the game servers: browse list, start/stop/restart instance etc

**Comment by markmandel** [comment]
Ah yes! Thanks for deeper explanation - lots of things going on, so great to have this here (and also when I come back to this after Cloud NEXT, it's easy to remember the context) - so appreciate the work.

That makes a lot of sense. I'm definitely not against doing this - I think long term I'd like to see much of that matchmaking 'where all servers' are equal flow into our multicluster work - wherein you can register your own local cluster with the wider cluster set (I have thoughts on this, I should write up a design ticket, just to get my basic thoughts out) - and that way you can do what you describe. 

That being said - having more control over allocations is definitely not a bad thing, and allows for differing types of workflows, especially as I don't think it would be particularly hard work.

re: the comment on micromanagement - you should be able to do this with no issue - you have access to the K8s api, so you can basically do whatever you want to any GameServers anywhere. - see [Accessing Agones via the Kubernetes API](https://github.com/GoogleCloudPlatform/agones/blob/master/docs/access_api.md) - although this could also be expanded into more examples.

**Comment by Kuqd** [comment]
when I was thinking about hint, it was more I want this type of machine, or I want this zone, which is covered by kubernetes by the way using affinity/anti-affinity/node-selector https://kubernetes.io/docs/concepts/configuration/assign-pod-node/.

Now it looks like the title is a bit off the discussion. If I understand correctly you want to be able to browse the list of available servers (browser mode), using the kubernetes API you can do that see @markmandel link, and allocate them by name could be a feature, again that seems simple. (Although nothing stops you from updating the ressource using k8s api)

> în which people can start servers at home that register to the session browser

However I'm wondering if servers out of  Kubernetes clusters is really within Agones scope. From my perspective the current allocations system is easier since you don't have to handle concurrency or allocate yourself.

Is there is really a need for this feature, if we don't support instance out of the cluster ? Should we first discuss if we want to support this type of server instance ?

**Comment by victor-prodan** [comment]
Just to make things clear, I wasn't talking about 'servers out of Kubernetes clusters'.

I am talking only about adding a simple filter to this iteration:

	for _, gs := range gsList {
		if gs.Status.State == stablev1alpha1.Ready && gs.ObjectMeta.DeletionTimestamp.IsZero() {
			allocation = gs
			break
		}
	}

Looks flexible enough to add filtering by server properties like name, labels, annotations etc .

**Comment by markmandel** [comment]
I was thinking about this more - does this lead down a path of having heterogeneous game server fleets?
(which is really against the idea of what we're trying to build).

Why not create seperate fleets if you want different types of game servers, and then have your matchmaker decide which fleet to allocate to? (based on their labels and annotations)?

Would that not work?

**Comment by victor-prodan** [comment]
More fleets you have more time and resources you waste managing them.

vin., 27 iul. 2018, 20:47 Mark Mandel <notifications@github.com> a scris:

**Comment by markmandel** [comment]
But as soon as you have heterogeneous fleets, you end up in the same place - you're just moving the place you are managing them, and making things more complicated, rather than less.

In fact, having multiple fleets, makes doing smoke testing, and even blue/green deployments of game servers that much easier - and much simpler concepts to manage at large. I definitely lean towards keeping things simple.

Also, we then also end up basically stepping away from core paradigms of Kubernetes and distributed systems - i.e. we want cattle, not pets.

I feel like we've moved away from the original premise - which is being able to allocate a specific GameServer instance - which I'm not against -- as there are existing matchmakers that already work on this premise, and we may want to support them.

I'm just not sure how large a demand there is for this (this is the first time I've seen it be requested), and it does break away from some of the core opinions of the project - so personally leaning towards a "wait and see" on how many people ask for this feature.

**Comment by CrimsonZen** [comment]
Since I was mentioned here, I should clarify what my use case was.

I wanted game servers to be able to allocate themselves so that I could use Agones's fleet scaling system—without changing my client code to talk to the Agones "server mamanager."

My players directly "look for an empty court," then walk on and start playing. I simply needed a tool that observed if more courts needed to be built on-the-fly, and knew which courts could be taken down.

**Comment by markmandel** [comment]
I was re-reading this thread, and realised something today.

You can do this now.

If you want to Allocate a specific `GameServer` - go to the Kubernetes API, and update the specific `GameServer` with the `Status > State` of "Allocated".

Voila. You don't actually need anything special on the Agones side. Just update the `State` yourself.

**Comment by markmandel** [comment]
@steven-supersolid Why don't you only allocate a `GameServer` when you have a complete party in your matchmaker?

Is there a particular reason you would allocate as each player requests a match and before they are grouped?

**Comment by steven-supersolid** [comment]
That's an option we discarded in an effort to simplify the system but can definitely revisit.

Our current approach is that our matchmaker does not know about or update state regarding queued players or desired party size and passes this responsibility on to the game server that they will be playing on. It is only aware of requested game mode, and state and mode of game server as reported via labels, e.g. `mode` and not `full`. The matchmaker is stateless and will be load balanced so by moving queue handling to the game server we remove some complexity.

There is no socket connection between the client and the matchmaker, so if a player drops out prior to a game then the game server is immediately aware of this and will wait until the party size reaches a threshold before moving from the `lobby` to `game` state. There is no need for the client to poll the matchmaker to see if the party is full and to keep a place in the queue. Although not a required feature, by performing queuing on the game server this enables real time communication between the players before the game starts.

With our current approach there is a possibility that the matchmaker may see a game server as not full and issue tokens to more players than there are spaces. We are using [netcode.io](https://github.com/networkprotocol/netcode.io/blob/master/STANDARD.md) which has a connection handshake mechanism so once a game server is full, any subsequent connection requests can be denied. A client can then request a new connection token from the matchmaker. If required, the matchmaker can issue connection tokens to multiple game servers and the client can then attempt to connect to each in turn until succeeding.

I don't know if this is a non-standard approach but it seemed like the simpler option at the time.

**Comment by markmandel** [comment]
@joeholley Do you have thoughts here -- since this seems to have moved into a matchmaker discussion, which I know is your area of focus.

I will likely end up closing this ticket, just because the functionality actually exists already through the k8s api -- but maybe this is another thing we should put in some kind of "tips and tricks" or "advanced guides" or similar documentation section?

**Comment by markmandel** [comment]
Now that we have `GameServerAllocation` - I think we can close this?

**Comment by markmandel** [comment]
Closing!
